apiVersion: deploy.ethzero.cloud/v1
kind: Site
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterName: ${CLUSTER_NAME}
  nodeImage: Ubuntu 20.04
  numMasters: 1
  numWorkers: 0
  runWorkloadOnMasters: true
