apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../config/crd
- ../../config/rbac
- ../../config/manager
namespace: site-deployer-system
namePrefix: site-deployer-
images:
- name: controller
  newName: foo/baz
  newTag: 1.2.6
