apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: site-deployer-dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Platform9-Community/site-deployer.git
    targetRevision: HEAD
    path: argo/dev
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - allowEmpty=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 15s
        maxDuration: 5m0s
        factor: 2
