name: Main
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      bump_app: ${{ steps.filter.outputs.bump_app }}
      bump_helm: ${{ steps.filter.outputs.bump_helm }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            bump_app:
              - 'cmd/**'

  bump_build_push:
    needs: detect_changes
    if: needs.detect_changes.outputs.bump_app == 'true'
    name: Bump Application Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Bump Application version in package.json
        id: version-bump-app
        uses: 'phips28/gh-action-bump-version@master'
        with:
          major-wording: 'major,MAJOR,breaking'
          minor-wording: 'feat,FEAT,minor,MINOR'
          patch-wording: 'fix,chore,test,docs,style,refactor,patch'
          rc-wording: 'RELEASE,alpha'
          skip-commit: 'true'
          skip-tag: 'true'
          skip-push: 'true'
          token: ${{ secrets.GH_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'cmd'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am 'CI(version) ${{ steps.version-bump-app.outputs.newTag }}'
          git tag ${{ steps.version-bump-app.outputs.newTag }}
          git push origin main ${{ steps.version-bump-app.outputs.newTag }}
      - name: Retrieve Docker Image Name with Tag
        run: |
          echo "::set-output name=IMG_NAME_AND_TAG::$(make docker_img_name_and_tag)"
        id: img_name_and_version_tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and publish Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.img_name_and_version_tag.outputs.IMG_NAME_AND_TAG }}
